apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-ceq-ekart-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: az-ceq-ekart-frontend
  template:
    metadata:
      labels:
        app: az-ceq-ekart-frontend
    spec:
      containers:
      - name: az-ceq-ekart-frontend
        image: manikanta26/az_ceq_ekart_frontend:v11
        env:
        - name: VITE_AUTH_API
          value: http://52.249.235.129:8000/api/v1
        - name: VITE_PROD_API
          value: http://ceq-ekart-product.eastus.azurecontainer.io:7001/api/v1/products
        - name: VITE_CART_API
          value: http://172.171.139.178:8001/api/v1
        - name: VITE_ORDER_API
          value: http://172.212.13.190:8002/api/v1/orders
        - name: VITE_NR_CART_IP
          value: http://172.171.139.178:8001
        - name: VITE_NR_ORDER_IP
          value: http://172.212.13.190:8002
        - name: VITE_NR_PROD_IP
          value: http://ceq-ekart-product.eastus.azurecontainer.io:7001
        - name: VITE_NR_USERS_IP
          value: http://52.249.235.129:8000
        ports:
        - containerPort: 5173
