apiVersion: v1
kind: Service
metadata:
  name: az-ceq-ekart-frontend
spec:
  type: LoadBalancer
  selector:
    app: az-ceq-ekart-frontend
    # app.kubernetes.io/name: MyApp
  ports:
  - protocol: TCP
    port: 5173
    targetPort: 5173
      